
"use client";

import React, { useState, useRef, useEffect, useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useToast } from '@/hooks/use-toast';
import { converseWithAppCreator } from '@/ai/flows/agentic-app-creator-flow';
import type { AppCreatorConversationRequest, Files } from '@/ai/schemas/agentic-app-creator-schemas';
import { 
    Bot, Menu, Download, Share2, Trash2, CodeXml, Eye, Github, RefreshCw, Save, Split, Send, Loader2
} from 'lucide-react';
import CodeBlock from '../chat/CodeBlock';
import { ScrollArea } from '../ui/scroll-area';
import { AnimatePresence, motion } from 'framer-motion';
import { Textarea } from '../ui/textarea';
import { Avatar, AvatarFallback } from '../ui/avatar';
import { cn } from '@/lib/utils';
import useIsMobile from '@/hooks/use-is-mobile';

type ViewMode = 'split' | 'preview' | 'code';
type Message = {
    role: 'user' | 'model';
    content: string;
};

const defaultFiles: Files = {
    'package.json': `{
  "name": "new-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "react": "latest",
    "react-dom": "latest",
    "next": "latest"
  },
"devDependencies": {
    "tailwindcss": "latest",
    "postcss": "latest",
    "autoprefixer": "latest"
  }
}`,
    'src/app/globals.css': `@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 222.2 84% 4.9%;
  }
  .dark {
    --background: 222.2 84% 4.9%;
    --foreground: 210 40% 98%;
  }
}`,
    'src/app/layout.tsx': `import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'My New App',
  description: 'Generated by AI',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}`,
    'src/app/page.tsx': `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold">My New App</h1>
      <p className="mt-4 text-lg text-muted-foreground">
        Get started by editing src/app/page.tsx
      </p>
    </main>
  )
}`,
};


const AgenticAppCreator = () => {
    const { toast } = useToast();
    const isMobile = useIsMobile();
    const [messages, setMessages] = useState<Message[]>([]);
    const [input, setInput] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [viewMode, setViewMode] = useState<ViewMode>('preview');
    const [generatedFiles, setGeneratedFiles] = useState<Files>(defaultFiles);
    const [previewContent, setPreviewContent] = useState('');
    const [isChatPanelVisible, setIsChatPanelVisible] = useState(true);

    const chatContainerRef = useRef<HTMLDivElement>(null);
    
    useEffect(() => {
        // This is a simplified mock preview.
        // A real implementation would require a secure sandbox and a proper React renderer.
        const pageTsx = generatedFiles['src/app/page.tsx'] || '';
        const globalsCss = generatedFiles['src/app/globals.css'] || '';
        
        const html = `
            <html>
                <head>
                    <script src="https://cdn.tailwindcss.com"></script>
                    <style>${globalsCss}</style>
                </head>
                <body class="bg-background text-foreground">
                    <div class="p-4">${pageTsx
                        // Super naive conversion for preview purposes only
                        .substring(pageTsx.indexOf('return') + 6)
                        .replace(/<main[^>]*>/, '<div class="flex min-h-screen flex-col items-center justify-center p-24">')
                        .replace(/<\/main>/, '</div>')
                        .replace(/className=/g, 'class=')
                        .replace(/<Image[^>]*\/>/g, '<div class="w-64 h-48 bg-muted rounded-lg flex items-center justify-center">Image Placeholder</div>')
                        .replace(/<[A-Z][^>]*\/>/g, (match) => `<div class="p-2 border rounded-md bg-muted/50">${match}</div>`)
                        .replace(/\\{/g, '')
                        .replace(/\\}/g, '')
                    }</div>
                </body>
            </html>
        `;
        setPreviewContent(html);

    }, [generatedFiles]);

    useEffect(() => {
        if (chatContainerRef.current) {
            chatContainerRef.current.scrollTop = chatContainerRef.current.scrollHeight;
        }
    }, [messages]);

    const handleSendMessage = useCallback(async () => {
        const userMessage = input.trim();
        if (!userMessage || isLoading) return;

        setInput('');
        setMessages(prev => [...prev, { role: 'user', content: userMessage }]);
        setIsLoading(true);

        try {
            const request: AppCreatorConversationRequest = {
                history: messages,
                prompt: userMessage,
            };
            const result = await converseWithAppCreator(request);
            
            setMessages(prev => [...prev, { role: 'model', content: result.response }]);

            if (result.generatedFiles) {
                setGeneratedFiles(prev => {
                    const updatedFiles: Partial<Files> = {};
                    for (const [key, value] of Object.entries(result.generatedFiles!)) {
                        if (value !== undefined) {
                            updatedFiles[key as keyof Files] = value;
                        }
                    }
                    return { ...prev, ...updatedFiles };
                });
                toast({
                    title: "Code Updated",
                    description: "The AI agent has updated the application files.",
                });
            }

        } catch (error) {
            console.error('Agentic App Creator failed:', error);
            const errorMessage = (error instanceof Error) ? error.message : 'An unknown error occurred.';
            setMessages(prev => [...prev, { role: 'model', content: `Sorry, an error occurred: ${errorMessage}` }]);
            toast({
                variant: 'destructive',
                title: 'An error occurred',
                description: 'Failed to communicate with the AI agent. Please try again.',
            });
        } finally {
            setIsLoading(false);
        }
    }, [input, isLoading, messages, toast]);


    const handleFeatureSoon = (featureName: string) => {
        toast({
            title: `Coming Soon: ${featureName}`,
            description: "We're working hard to add this feature. Stay tuned!",
        });
    }
    
    const renderChatPanel = () => (
        <div className={cn(
            "flex flex-col border-r bg-slate-50 dark:bg-black",
            "h-full w-full md:w-[450px]",
            !isChatPanelVisible && "hidden"
        )}>
            <ScrollArea className="flex-1" ref={chatContainerRef}>
                <div className="p-4 space-y-4">
                    {messages.length === 0 && (
                         <div className="flex items-start gap-3">
                             <Avatar className='w-8 h-8'><AvatarFallback><Bot /></AvatarFallback></Avatar>
                             <div className="max-w-md p-3 rounded-lg bg-muted">
                                <p className="text-sm">Welcome to the App Creator! Describe the application you want to build, and I'll generate the code for you.</p>
                            </div>
                        </div>
                    )}
                    {messages.map((msg, index) => (
                        <motion.div
                            key={index}
                            initial={{ opacity: 0, y: 10 }}
                            animate={{ opacity: 1, y: 0 }}
                        >
                            <div className={cn("flex items-start gap-3", msg.role === 'user' ? 'justify-end' : 'justify-start')}>
                                {msg.role === 'model' && <Avatar className='w-8 h-8'><AvatarFallback><Bot /></AvatarFallback></Avatar>}
                                <div className={cn(
                                    "max-w-md p-3 rounded-lg prose dark:prose-invert prose-sm",
                                    msg.role === 'user' ? 'bg-primary text-primary-foreground' : 'bg-muted'
                                )}>
                                    <p className="whitespace-pre-wrap">{msg.content}</p>
                                </div>
                            </div>
                        </motion.div>
                    ))}
                    {isLoading && (
                        <div className="flex items-center gap-3">
                             <Avatar className='w-8 h-8'><AvatarFallback><Bot /></AvatarFallback></Avatar>
                             <Loader2 className="w-5 h-5 animate-spin" />
                        </div>
                    )}
                </div>
            </ScrollArea>
            <div className="p-4 border-t">
                <div className="relative">
                    <Textarea 
                        placeholder="Describe the app you want to build..."
                        value={input}
                        onChange={e => setInput(e.target.value)}
                        onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleSendMessage(); }}}
                        className="pr-12 rounded-lg"
                        rows={1}
                    />
                    <Button 
                        type="submit" 
                        size="icon" 
                        className="absolute right-2 top-1/2 -translate-y-1/2 rounded-full"
                        onClick={handleSendMessage}
                        disabled={isLoading || !input.trim()}
                    >
                        <Send className="h-4 w-4" />
                    </Button>
                </div>
            </div>
        </div>
    );
    
    const renderContentPanel = () => (
         <div className={cn(
            "flex-1 bg-slate-100 dark:bg-slate-900",
             isChatPanelVisible && isMobile && "hidden"
        )}>
             {viewMode === 'preview' && (
                 <iframe
                    srcDoc={previewContent}
                    title="App Preview"
                    sandbox="allow-scripts"
                    className="w-full h-full border-none bg-white"
                />
            )}
             {viewMode === 'code' && (
                <Tabs defaultValue={Object.keys(generatedFiles)[3]} className="w-full h-full flex flex-col">
                    <TabsList className="grid w-full grid-cols-2 md:grid-cols-4 shrink-0">
                        {Object.keys(generatedFiles).map(filename => (
                            <TabsTrigger key={filename} value={filename}>{filename.replace('src/app/', '')}</TabsTrigger>
                        ))}
                    </TabsList>
                    {Object.entries(generatedFiles).map(([filename, content]) => (
                         <TabsContent key={filename} value={filename} className="flex-1 overflow-y-auto">
                            <CodeBlock code={`\`\`\`tsx\n${content}\n\`\`\``} />
                        </TabsContent>
                    ))}
                </Tabs>
            )}
        </div>
    );

    const renderMenu = () => (
        <>
            <SheetHeader>
                <SheetTitle>App Actions</SheetTitle>
                <SheetDescription>Manage your generated application.</SheetDescription>
            </SheetHeader>
            <div className="flex flex-col gap-2 py-4">
                <Button variant="outline" className="justify-start" onClick={() => handleFeatureSoon('Publish to GitHub')}>
                    <Github className="mr-2 h-4 w-4" /> Publish to GitHub
                </Button>
                <Button variant="outline" className="justify-start" onClick={() => handleFeatureSoon('Download Files')}>
                    <Download className="mr-2 h-4 w-4" /> Download Files
                </Button>
                <Button variant="outline" className="justify-start" onClick={() => handleFeatureSoon('Share App')}>
                    <Share2 className="mr-2 h-4 w-4" /> Share App
                </Button>
                <Button variant="outline" className="justify-start" onClick={() => handleFeatureSoon('Save App')}>
                    <Save className="mr-2 h-4 w-4" /> Save App
                </Button>
                 <Button variant="outline" className="justify-start" onClick={() => {
                    setGeneratedFiles(defaultFiles);
                    setMessages([]);
                    toast({ description: "App has been reset to its initial state." });
                }}>
                    <RefreshCw className="mr-2 h-4 w-4" /> Reset
                </Button>
                 <Button variant="destructive" className="justify-start" onClick={() => handleFeatureSoon('Delete App')}>
                    <Trash2 className="mr-2 h-4 w-4" /> Delete App
                </Button>
            </div>
        </>
    );

    return (
        <div className="w-full h-full flex flex-col" dir="ltr">
            {/* Header */}
            <header className="flex items-center justify-between p-2 border-b shrink-0">
                 <div className='flex items-center gap-2'>
                    <Sheet>
                        <SheetTrigger asChild>
                             <Button variant="ghost" size="icon"><Menu /></Button>
                        </SheetTrigger>
                        <SheetContent side="left">{renderMenu()}</SheetContent>
                    </Sheet>
                    <h1 className="font-semibold text-lg hidden sm:block">AI App Creator</h1>
                 </div>
                 <div className="flex items-center gap-2 p-1 bg-muted rounded-full">
                    {isMobile && (
                        <Button size="sm" variant={isChatPanelVisible ? 'secondary' : 'ghost'} className="rounded-full" onClick={() => setIsChatPanelVisible(true)}>
                            <Bot className="mr-2 h-4 w-4" />Chat
                        </Button>
                    )}
                    <Button size="sm" variant={viewMode === 'preview' && !isChatPanelVisible ? 'secondary' : 'ghost'} className="rounded-full" onClick={() => { setViewMode('preview'); setIsChatPanelVisible(false); }}>
                        <Eye className="mr-2 h-4 w-4" />Preview
                    </Button>
                    <Button size="sm" variant={viewMode === 'code' && !isChatPanelVisible ? 'secondary' : 'ghost'} className="rounded-full" onClick={() => { setViewMode('code'); setIsChatPanelVisible(false); }}>
                        <CodeXml className="mr-2 h-4 w-4" />Code
                    </Button>
                 </div>
            </header>

            {/* Main Content */}
            <main className="flex-1 flex flex-col md:flex-row overflow-hidden">
                {renderChatPanel()}
                {renderContentPanel()}
            </main>
        </div>
    );
};

export default AgenticAppCreator;

    