
"use client";

import React, { useState, useRef, useEffect, useCallback } from 'react';
import { Button } from '@/components/ui/button';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, SheetTrigger } from '@/components/ui/sheet';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useToast } from '@/hooks/use-toast';
import { converseWithAppCreator, AppCreatorConversationResponse, AppCreatorConversationRequest } from '@/ai/flows/agentic-app-creator-flow';
import { 
    Bot, Menu, Download, Share2, Trash2, CodeXml, Eye, Github, RefreshCw, Save, Split, ArrowUp, Loader2, Sparkles, Send
} from 'lucide-react';
import CodeBlock from '../chat/CodeBlock';
import Image from 'next/image';
import { ScrollArea } from '../ui/scroll-area';
import { AnimatePresence, motion } from 'framer-motion';
import { Textarea } from '../ui/textarea';

type ViewMode = 'split' | 'preview' | 'code';
type Message = {
    role: 'user' | 'model';
    content: string;
};

const defaultFiles = {
    'package.json': `{
  "name": "new-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "react": "latest",
    "react-dom": "latest",
    "next": "latest"
  }
}`,
    'src/app/globals.css': `@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: 0 0% 100%;
    --foreground: 222.2 84% 4.9%;
  }
  .dark {
    --background: 222.2 84% 4.9%;
    --foreground: 210 40% 98%;
  }
}`,
    'src/app/layout.tsx': `import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'My New App',
  description: 'Generated by AI',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}`,
    'src/app/page.tsx': `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold">My New App</h1>
      <p className="mt-4 text-lg text-muted-foreground">
        Get started by editing src/app/page.tsx
      </p>
    </main>
  )
}`,
};


const AgenticAppCreator = () => {
    const { toast } = useToast();
    const [messages, setMessages] = useState<Message[]>([]);
    const [input, setInput] = useState('');
    const [isLoading, setIsLoading] = useState(false);
    const [viewMode, setViewMode] = useState<ViewMode>('preview');
    const [generatedFiles, setGeneratedFiles] = useState<Record<string, string>>(defaultFiles);
    const [previewContent, setPreviewContent] = useState('');

    const chatContainerRef = useRef<HTMLDivElement>(null);
    
    // Create a mock iframe preview content
    useEffect(() => {
        const pageTsx = generatedFiles['src/app/page.tsx'] || '';
        const globalsCss = generatedFiles['src/app/globals.css'] || '';
        // A very simplified way to get JSX out of a TSX file string.
        // This is not a real renderer and has many limitations.
        const jsxContent = pageTsx.substring(pageTsx.indexOf('return') + 6).trim().replace(/;$/, '');

        // For a more robust preview, we would need a proper sandbox.
        // This is a simplified mock.
        const html = `
            <html>
                <head>
                    <style>
                        @import url('https://cdn.tailwindcss.com');
                        ${globalsCss}
                    </style>
                </head>
                <body class="bg-background text-foreground">
                    <div id="root"></div>
                    <script type="module">
                        // This is a mock script to render a static view. It won't work for real.
                        // A real implementation would need a secure sandbox and React renderer.
                        const content = \`${jsxContent.replace(/`/g, '\\`')}\`;
                        // A very crude way to convert JSX-like string to HTML string for demo
                        let htmlContent = content.replace(/className=/g, 'class=');
                        htmlContent = htmlContent.replace(/<\\/main>/g, '</div>');
                        htmlContent = htmlContent.replace(/<main.*?>/g, '<div class="flex min-h-screen flex-col items-center justify-center p-24">');
                        document.getElementById('root').innerHTML = htmlContent;
                    </script>
                </body>
            </html>
        `;
        setPreviewContent(html);

    }, [generatedFiles]);

    useEffect(() => {
        if (chatContainerRef.current) {
            chatContainerRef.current.scrollTop = chatContainerRef.current.scrollHeight;
        }
    }, [messages]);

    const handleSendMessage = useCallback(async () => {
        const userMessage = input.trim();
        if (!userMessage || isLoading) return;

        setInput('');
        setMessages(prev => [...prev, { role: 'user', content: userMessage }]);
        setIsLoading(true);

        try {
            const request: AppCreatorConversationRequest = {
                history: messages,
                prompt: userMessage,
            };
            const result = await converseWithAppCreator(request);
            
            setMessages(prev => [...prev, { role: 'model', content: result.response }]);

            if (result.generatedFiles) {
                setGeneratedFiles(prev => ({ ...prev, ...result.generatedFiles }));
                toast({
                    title: "Code Updated",
                    description: "The AI agent has updated the application files.",
                });
            }

        } catch (error) {
            console.error('Agentic App Creator failed:', error);
            const errorMessage = (error instanceof Error) ? error.message : 'An unknown error occurred.';
            setMessages(prev => [...prev, { role: 'model', content: `Sorry, an error occurred: ${errorMessage}` }]);
            toast({
                variant: 'destructive',
                title: 'An error occurred',
                description: 'Failed to communicate with the AI agent. Please try again.',
            });
        } finally {
            setIsLoading(false);
        }
    }, [input, isLoading, messages, toast]);


    const handleFeatureSoon = (featureName: string) => {
        toast({
            title: `Coming Soon: ${featureName}`,
            description: "We're working hard to add this feature. Stay tuned!",
        });
    }

    const renderMenu = () => (
        <>
            <SheetHeader>
                <SheetTitle>App Actions</SheetTitle>
                <SheetDescription>Manage your generated application.</SheetDescription>
            </SheetHeader>
            <div className="flex flex-col gap-2 py-4">
                <Button variant="outline" className="justify-start" onClick={() => handleFeatureSoon('Publish to GitHub')}>
                    <Github className="mr-2 h-4 w-4" /> Publish to GitHub
                </Button>
                <Button variant="outline" className="justify-start" onClick={() => handleFeatureSoon('Download Files')}>
                    <Download className="mr-2 h-4 w-4" /> Download Files
                </Button>
                <Button variant="outline" className="justify-start" onClick={() => handleFeatureSoon('Share App')}>
                    <Share2 className="mr-2 h-4 w-4" /> Share App
                </Button>
                <Button variant="outline" className="justify-start" onClick={() => handleFeatureSoon('Save App')}>
                    <Save className="mr-2 h-4 w-4" /> Save App
                </Button>
                 <Button variant="outline" className="justify-start" onClick={() => {
                    setGeneratedFiles(defaultFiles);
                    setMessages([]);
                    toast({ description: "App has been reset to its initial state." });
                }}>
                    <RefreshCw className="mr-2 h-4 w-4" /> Reset
                </Button>
                 <Button variant="destructive" className="justify-start" onClick={() => handleFeatureSoon('Delete App')}>
                    <Trash2 className="mr-2 h-4 w-4" /> Delete App
                </Button>
            </div>
        </>
    );

    return (
        <div className="w-full h-full flex flex-col" dir="ltr">
            {/* Header */}
            <header className="flex items-center justify-between p-2 border-b shrink-0">
                 <div className='flex items-center gap-2'>
                    <Sheet>
                        <SheetTrigger asChild>
                             <Button variant="ghost" size="icon"><Menu /></Button>
                        </SheetTrigger>
                        <SheetContent side="left">{renderMenu()}</SheetContent>
                    </Sheet>
                    <h1 className="font-semibold text-lg">AI App Creator</h1>
                 </div>
                 <div className="flex items-center gap-2 p-1 bg-muted rounded-full">
                    <Button size="sm" variant={viewMode === 'split' ? 'secondary' : 'ghost'} className="rounded-full" onClick={() => setViewMode('split')}><Split className="mr-2 h-4 w-4" />Split</Button>
                    <Button size="sm" variant={viewMode === 'preview' ? 'secondary' : 'ghost'} className="rounded-full" onClick={() => setViewMode('preview')}><Eye className="mr-2 h-4 w-4" />Preview</Button>
                    <Button size="sm" variant={viewMode === 'code' ? 'secondary' : 'ghost'} className="rounded-full" onClick={() => setViewMode('code')}><CodeXml className="mr-2 h-4 w-4" />Code</Button>
                 </div>
            </header>

            {/* Main Content */}
            <main className="flex-1 flex overflow-hidden">
                {/* Chat Panel */}
                <div className={cn(
                    "flex flex-col border-r bg-slate-50 dark:bg-black",
                    viewMode === 'split' ? "w-1/2" : (viewMode === 'preview' || viewMode === 'code') ? "hidden" : "w-full"
                )}>
                    <ScrollArea className="flex-1" ref={chatContainerRef}>
                        <div className="p-4 space-y-4">
                            {messages.map((msg, index) => (
                                <motion.div
                                    key={index}
                                    initial={{ opacity: 0, y: 10 }}
                                    animate={{ opacity: 1, y: 0 }}
                                >
                                    <div className={cn("flex items-start gap-3", msg.role === 'user' ? 'justify-end' : 'justify-start')}>
                                        {msg.role === 'model' && <Avatar className='w-8 h-8'><AvatarFallback><Bot /></AvatarFallback></Avatar>}
                                        <div className={cn(
                                            "max-w-md p-3 rounded-lg",
                                            msg.role === 'user' ? 'bg-primary text-primary-foreground' : 'bg-muted'
                                        )}>
                                            <p className="text-sm whitespace-pre-wrap">{msg.content}</p>
                                        </div>
                                    </div>
                                </motion.div>
                            ))}
                            {isLoading && (
                                <div className="flex items-center gap-3">
                                     <Avatar className='w-8 h-8'><AvatarFallback><Bot /></AvatarFallback></Avatar>
                                     <Loader2 className="w-5 h-5 animate-spin" />
                                </div>
                            )}
                        </div>
                    </ScrollArea>
                    <div className="p-4 border-t">
                        <div className="relative">
                            <Textarea 
                                placeholder="Describe the app you want to build or the changes you want to make..."
                                value={input}
                                onChange={e => setInput(e.target.value)}
                                onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleSendMessage(); }}}
                                className="pr-12 rounded-full"
                                rows={1}
                            />
                            <Button 
                                type="submit" 
                                size="icon" 
                                className="absolute right-2 top-1/2 -translate-y-1/2 rounded-full"
                                onClick={handleSendMessage}
                                disabled={isLoading || !input.trim()}
                            >
                                <Send className="h-4 w-4" />
                            </Button>
                        </div>
                    </div>
                </div>

                {/* Preview / Code Panel */}
                <div className={cn(
                    "flex-1 bg-slate-100 dark:bg-slate-800",
                    viewMode === 'split' ? "w-1/2" : "w-full"
                )}>
                    {viewMode !== 'code' ? (
                         <iframe
                            srcDoc={previewContent}
                            title="App Preview"
                            sandbox="allow-scripts"
                            className="w-full h-full border-none bg-white"
                        />
                    ) : (
                        <Tabs defaultValue={Object.keys(generatedFiles)[3]} className="w-full h-full flex flex-col">
                            <TabsList className="grid w-full grid-cols-2 md:grid-cols-4 shrink-0">
                                {Object.keys(generatedFiles).map(filename => (
                                    <TabsTrigger key={filename} value={filename}>{filename.replace('src/app/', '')}</TabsTrigger>
                                ))}
                            </TabsList>
                            {Object.entries(generatedFiles).map(([filename, content]) => (
                                 <TabsContent key={filename} value={filename} className="flex-1 overflow-y-auto">
                                    <CodeBlock code={`\`\`\`tsx\n${content}\n\`\`\``} />
                                </TabsContent>
                            ))}
                        </Tabs>
                    )}
                </div>
            </main>
        </div>
    );
};

export default AgenticAppCreator;
